# Generated by Django 4.1.7 on 2023-04-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_scrapers", "0002_rename_country_history_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
