# Generated by Django 4.1.7 on 2023-04-04 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map_scrapers", "0003_alter_history_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="history",
            options={"ordering": ["-timestamp"]},
        ),
    ]
