# Generated by Django 4.1.7 on 2023-04-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_scrapers", "0004_alter_history_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="history",
            name="address",
        ),
        migrations.AddField(
            model_name="history",
            name="average_rating",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="categories",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="cid",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="full_address",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="google_map_url",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="latitude",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="longitude",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="opening_hours",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="phones",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="place_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="review_count",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="reviews_url",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="street",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="history",
            name="business_name",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="history",
            name="website",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
