# Generated by Django 4.1.7 on 2023-04-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_scrapers", "0005_remove_history_address_history_average_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="social_media_links",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="history",
            name="email",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
