# Generated by Django 4.1.7 on 2023-04-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_scrapers", "0006_history_social_media_links_alter_history_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="municipality",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="history",
            name="plus_code",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
