# Generated by Django 4.1.7 on 2023-04-18 09:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("map_scrapers", "0008_searchinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="search_info",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="map_scrapers.searchinfo",
            ),
        ),
        migrations.AddField(
            model_name="searchinfo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="searchinfo",
            name="keyword",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="searchinfo",
            name="platform",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="searchinfo",
            name="scraped_places",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="searchinfo",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="searchinfo",
            name="total_places",
            field=models.IntegerField(default=0),
        ),
    ]
