# Generated by Django 4.1.7 on 2023-04-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_scrapers", "0009_history_search_info_searchinfo_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchinfo",
            name="location",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
