# Generated by Django 4.1.7 on 2023-04-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map_scrapers", "0010_searchinfo_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchinfo",
            options={"ordering": ["-timestamp"]},
        ),
    ]
