# Generated by Django 4.1.7 on 2023-05-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_jobs_progress_alter_jobs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
