# Generated by Django 4.1.7 on 2023-05-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_jobs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='user',
            field=models.CharField(max_length=300),
        ),
    ]
