# Generated by Django 4.1.7 on 2023-05-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_jobs_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='credits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('available', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
