# Generated by Django 4.1.7 on 2023-05-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_credits_date_credits_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credits',
            name='time',
        ),
        migrations.AddField(
            model_name='credits',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
