# Generated by Django 4.1.7 on 2023-05-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_credits_time_credits_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='progress',
            field=models.CharField(max_length=110),
        ),
    ]
